### ISSUE TITLE
This is something I wanted to try for a long time

### ISSUE THREAD

**Issue by ands** [jkoenen/imgui_native#1]
Looks like a small test thingie unless I'm missing something. How did this work out? :)

**Comment by aggsol** [comment]
Maybe this is also of interest for you as it packs ImGui into nativ Windows windows: https://github.com/thennequin/ImWindow

![Example](https://raw.githubusercontent.com/thennequin/ImWindow/master/Screenshots/Docking.gif)

**Comment by ands** [comment]
I have seen ImWindow, but I thought this repo was actually an attempt at creating a native widgets backend for an imgui api :)

**Comment by jkoenen** [comment]
Yes, it was... But we decided to not use a native backend for our internal imgui system in the end.. It was just a simple experiment

**Comment by ands** [comment]
Alright!
